default = (
    'misc.messages',
    'misc.source',
    'misc.ocr',
    'misc.fxtwitter',
    'misc.invite',
    'misc.random',
    'misc.manga',
    'misc.bin',
    'management.modules',
    'management.autothread',
    'management.autopublish',
    'moderation.purge',
    'gacha.headquarters',
)