CACHE_TTL = 300

RANDOMS = {
    'song': [
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://www.youtube.com/watch?v=7ZtepNkPzcM',
        'https://www.youtube.com/watch?v=rEjLrKdORVg',
        'https://www.youtube.com/watch?v=MvUt77FCCjE',
        'https://www.youtube.com/watch?v=fnYO8ff7L3M',
        'https://www.youtube.com/watch?v=wGRaeC3gsLg',
        'https://www.youtube.com/watch?v=JBG55CfTZ9w',
        'https://www.youtube.com/watch?v=ByBkaWQzLT4',
        'https://www.youtube.com/watch?v=i6P_VO01w4Q',
        'https://www.youtube.com/watch?v=1zrKM01rBkU',
        'https://www.youtube.com/watch?v=aDQKlCWleVE',
        'https://www.youtube.com/watch?v=cixnLVRRVK0',
        'https://www.youtube.com/watch?v=BXuCcL3pL1E',
        'https://www.youtube.com/watch?v=XXP9f-rfm-g',
        'https://open.spotify.com/track/2oIwlCLMTmNm21n1V16phB?si=d3c43d2b387e403d',
        'https://open.spotify.com/track/7d01oOW0gldyGW8hlUVN1J?si=89e2adebd2404dc6',
        'https://open.spotify.com/track/0WeFvEY2QEjcKVd8ymli4i?si=59e9950476fe49cc',
        'https://open.spotify.com/track/0tBQVOAtBpqdQK2ExkbHZX?si=85c3ce411d47421b',
        'https://open.spotify.com/track/1gewwJHPkvysxLEGgOKQuB?si=75e05f98853e4df7',
        'https://open.spotify.com/track/1c03f9YZmO792D7hRjZMYi?si=6128997e64e04040',
        'https://open.spotify.com/track/05IyD7K9Q4lgu8W4Xfi9Lx?si=1eb86978fe994afd',
        'https://open.spotify.com/track/5EwWFDHwehCMl5h1zJHAr2?si=2ef4966b986c453d',
        'https://open.spotify.com/track/79fspqGOIP7FInu1elXhVX?si=1158a53892ae4382',
        'https://open.spotify.com/track/7doVh2YbnJammAiJ3YmYSi?si=0237bcbc03614ac4',
        'https://open.spotify.com/track/1PyRHSdxEZgJpN3vWSGNFw?si=0a6fbd73508a4c7a',
        'https://open.spotify.com/track/0eYUPGR0tB6pP5YvE3zXaU?si=b6f5d0a8f0c24d15',
        'https://open.spotify.com/track/6NndAdLoSF1fcFtbRlGMLt?si=b46fd0fdba4b4677',
        'https://www.youtube.com/watch?v=tIG-cXkrdnQ',
        'https://www.youtube.com/watch?v=5qdFjGI9948',

    ],
    'meme': [
        'https://www.youtube.com/watch?v=lpXqBLBxG18',
        'https://www.youtube.com/watch?v=4kqbKEqzsAI',
        'https://www.youtube.com/watch?v=ivEm-Tjo6GM',
        'https://www.youtube.com/watch?v=Pz459FEsSKM',
        'https://www.youtube.com/watch?v=kN3L1lchpdA',
        'https://www.youtube.com/watch?v=JFLdUjQvKb4',
        'https://www.youtube.com/watch?v=6llwDj67VOw',
        'https://www.youtube.com/watch?v=tTd4W0_7FfY',
        'https://www.youtube.com/watch?v=iGJTFfcyLVU',
        'https://www.youtube.com/watch?v=lDRjqI-fBVI',
        'https://www.youtube.com/watch?v=KtRZ-3kLM6A',
        'https://www.youtube.com/watch?v=KYx4s48jw8M',
        'https://www.youtube.com/watch?v=wDI6lBUyoeI',
        'https://www.youtube.com/watch?v=R2kovI6tpRE',
        'https://www.youtube.com/watch?v=TcZwHFW1Ku4',
        'https://www.youtube.com/watch?v=yYiVlpmLKjI',
        'https://www.youtube.com/watch?v=md8nInMGhFY',
    ],
    'video': [
        'https://www.youtube.com/watch?v=K-aS5M-F9eM',
        'https://www.youtube.com/watch?v=ezSdQ63phFw',
        'https://www.youtube.com/watch?v=Yl1FNX08HFc',
        'https://www.youtube.com/watch?v=G30xZxJLR8U',
        'https://www.youtube.com/watch?v=C9bj1w63rf8',
        'https://www.youtube.com/watch?v=c4x_X6IXKqY',
        'https://www.youtube.com/watch?v=PqNfhQ5JYnc',
        'https://www.youtube.com/watch?v=5gTAr2HlmM8',
        'https://www.youtube.com/watch?v=EZbLWePLQVc',
        'https://www.youtube.com/watch?v=VsH61rkSmpY',
        'https://www.youtube.com/watch?v=O2hATreQj7M',
        'https://www.youtube.com/watch?v=98TyXgg-mIg',
        'https://www.youtube.com/watch?v=euNx2IXSirY',
        'https://www.youtube.com/watch?v=3IT_rnV1LBw',
        'https://www.youtube.com/watch?v=1jpuNAYcS2o'
    ]
}